/* eslint-disable prettier/prettier */
export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const CIERRE_REPOSITORY = 'CIERRE_REPOSITORY';
export const CONTRATO_REPOSITORY = 'CONTRATO_REPOSITORY';
export const INFCONTRATO_REPOSITORY = 'INFCONTRATO_REPOSITORY';
export const INVERSIONISTA_REPOSITORY = 'INVERSIONISTA_REPOSITORY';
export const OBRA_REPOSITORY = 'OBRA_REPOSITORY';
export const PLANANUAL_REPOSITORY = 'PLANANUAL_REPOSITORY';
export const PLANPRE_REPOSITORY = 'PLANPRE_REPOSITORY';
export const REGISTRO_REPOSITORY = 'REGISTROCONTABILIDAD_REPOSITORY';
export const RESUMEN_REPOSITORY = 'RESUMEN_REPOSITORY';
export const SUBCONTRATA_REPOSITORY = 'SUBCONTRATA_REPOSITORY';
export const SUBOBRA_REPOSITORY = 'SUBOBRA_REPOSITORY';
export const USER_AUTH_REPOSITORY = 'USER_AUTH_REPOSITORY';
export const secret = {
    secret: 'mfkdm5454KJJmimi909KHHJJnnnmnLJ'
}